### ISSUE TITLE
$profile: Handle confusables in player names like DDNet does

### ISSUE THREAD

**Issue by 12pm** [12pm/ddnet-discordbot#2]

**Comment by heinrich5991** [comment]
DDNet doesn't handle them, one [1](https://ddnet.tw/players/1/), uppercase i [l](https://ddnet.tw/players/I/) and lowercase L [l](https://ddnet.tw/players/l/) are all different player names for the DDNet database. They just can't play on the same server at the same time.

**Comment by 12pm** [comment]
thanks for clarifying this :)
